# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Marco Mangiante
tagline:             'Blog su Windows e dintorni'
description:         'Un sistemista IT e Microsoft'
url:                 http://www.professione.com
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              Marco Mangiante
  url:               https://twitter.com/marcomangiante
  email:             marcomangiante@hotmail.com

# Custom vars
version:             1.0.0

# Permit post excerpt
excerpt_separator: "<!--more-->"

# Gems

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
